import Head from 'next/head'
import { LiquidityModal } from '../src/components/liquidityModal'
import Connect2Phantom from '../src/components/phantomConnector'
import { useConnection } from '../src/hooks/useConnection'
import { RaySolPool, usePool } from '../src/hooks/usePool'
import styles from '../styles/Home.module.css'

export default function Home() {
    const { connection } = useConnection()
    const { token1Amount, token2Amount } = usePool(connection, RaySolPool)

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Connect2Phantom />

                <LiquidityModal token1Amount={token1Amount} token2Amount={token2Amount} />
            </main>
        </div>
    )
}
